name: Deploy

on:
  repository_dispatch:
    types: [TEST_FINISH_TRIGGER]
    
jobs:
  build:
    name: Build
    runs-on: ubunutu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello!"
